package hello;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

// import org.springframework.data.repository.ID;

@RestController    // This means that this class is a Controller
@RequestMapping(path = "/todos") // This means URL's start with /demo (after Application path)
public class TodoController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private TodoRepository TodoRepository;

    @PostMapping(path = "/add")
    public @ResponseBody Todo addNewTodo(@RequestBody Todo todo) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        try {
            TodoRepository.save(todo);
        } catch (Exception e) {
        }
        return todo;
    }

    @GetMapping(path = "/get")
    public @ResponseBody
    Iterable<Todo> getAllTodos() {
        // This returns a JSON or XML with the users
        return TodoRepository.findAll();
    }

    @GetMapping(path = "/get/{id}")
    public Todo getTodoById(@PathVariable Integer id) {
        return TodoRepository.findById(id).get();
    }

    @PutMapping(path = "/change/{id}")
    public Todo replaceTodoById(@RequestBody Todo newTodo,@PathVariable Integer id){
        return TodoRepository.findById(id).map(todo->{
            todo.setText(newTodo.getText());
            todo.setDone(newTodo.getDone());
            return TodoRepository.save(todo);
        }).orElseGet(()->{
            newTodo.setId(id);
            return TodoRepository.save(newTodo);
        });
    }

    @DeleteMapping(path = "/delete/{id}")
    public String deletTodoById(@PathVariable Integer id){
        TodoRepository.delete(TodoRepository.findById(id).get());
        return "Todo @"+id+" successfully removed";
    }
}
