package hello;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.RestController;

import hello.Todo;
import hello.TodoRepository;

@RestController    // This means that this class is a Controller
@RequestMapping(path="/todos") // This means URL's start with /demo (after Application path)
public class TodoController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private TodoRepository TodoRepository;

	@CrossOrigin(origins = "http://localhost:8080")
	@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewTodo (@RequestParam String text
			, @RequestParam Boolean done) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Todo n = new Todo();
		n.setText(text);
		n.setDone(done);
		TodoRepository.save(n);
		return "Saved";
	}

	@CrossOrigin(origins = "http://localhost:8080")
	@GetMapping(path="/get")
	public @ResponseBody Iterable<Todo> getAllTodos() {
		// This returns a JSON or XML with the users
		return TodoRepository.findAll();
	}
}
