package hello;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

// import org.springframework.data.repository.ID;

@CrossOrigin(origins = "*")
@RestController    // This means that this class is a Controller
@RequestMapping(path = "/todos") // This means URL's start with /demo (after Application path)
public class TodoController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private TodoRepository TodoRepository;

    @PostMapping(path = "/add")
    public @ResponseBody Todo addNewTodo(@RequestBody Todo todo) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        try {
            TodoRepository.save(todo);
        } catch (Exception e) {
        }
        return todo;
    }

    @GetMapping(path = "/get")
    public @ResponseBody
    Iterable<Todo> getAllTodos() {
        // This returns a JSON or XML with the users
        return TodoRepository.findAll();
    }

    @GetMapping(path = "/")
    public java.util.Optional<Todo> getTodoById(@PathVariable Integer id) {
        return TodoRepository.findById(id);
    }
}
